// CodeGear C++Builder
// Copyright (c) 1995, 2022 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'dxSkinsStrs.pas' rev: 35.00 (Windows)

#ifndef DxskinsstrsHPP
#define DxskinsstrsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <cxGraphics.hpp>
#include <cxGeometry.hpp>
#include <cxLookAndFeelPainters.hpp>

//-- user supplied -----------------------------------------------------------

namespace Dxskinsstrs
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
typedef System::StaticArray<System::UnicodeString, 22> Dxskinsstrs__1;

typedef System::StaticArray<System::UnicodeString, 6> Dxskinsstrs__2;

typedef System::StaticArray<System::UnicodeString, 28> Dxskinsstrs__3;

typedef System::StaticArray<System::UnicodeString, 4> Dxskinsstrs__4;

typedef System::StaticArray<System::UnicodeString, 4> Dxskinsstrs__5;

typedef System::StaticArray<System::UnicodeString, 26> Dxskinsstrs__6;

typedef System::StaticArray<System::UnicodeString, 11> Dxskinsstrs__7;

typedef System::StaticArray<System::UnicodeString, 15> Dxskinsstrs__8;

typedef System::StaticArray<System::UnicodeString, 5> Dxskinsstrs__9;

typedef System::StaticArray<System::UnicodeString, 14> Dxskinsstrs__01;

typedef System::StaticArray<System::UnicodeString, 8> Dxskinsstrs__11;

typedef System::StaticArray<System::StaticArray<System::UnicodeString, 4>, 2> Dxskinsstrs__21;

typedef System::StaticArray<System::UnicodeString, 4> Dxskinsstrs__31;

typedef System::StaticArray<System::UnicodeString, 4> Dxskinsstrs__41;

typedef System::StaticArray<System::UnicodeString, 6> Dxskinsstrs__51;

typedef System::StaticArray<System::UnicodeString, 6> Dxskinsstrs__61;

typedef System::StaticArray<System::UnicodeString, 4> Dxskinsstrs__71;

//-- var, const, procedure ---------------------------------------------------
extern DELPHI_PACKAGE System::ResourceString _sdxOldFormat;
#define Dxskinsstrs_sdxOldFormat System::LoadResourceString(&Dxskinsstrs::_sdxOldFormat)
extern DELPHI_PACKAGE System::ResourceString _sdxSkinInvalidStreamFormat;
#define Dxskinsstrs_sdxSkinInvalidStreamFormat System::LoadResourceString(&Dxskinsstrs::_sdxSkinInvalidStreamFormat)
extern DELPHI_PACKAGE System::ResourceString _sdxSkinElementNotFound;
#define Dxskinsstrs_sdxSkinElementNotFound System::LoadResourceString(&Dxskinsstrs::_sdxSkinElementNotFound)
extern DELPHI_PACKAGE System::ResourceString _sdxSkinGroupNotFound;
#define Dxskinsstrs_sdxSkinGroupNotFound System::LoadResourceString(&Dxskinsstrs::_sdxSkinGroupNotFound)
extern DELPHI_PACKAGE System::ResourceString _sdxSkinParentNotFound;
#define Dxskinsstrs_sdxSkinParentNotFound System::LoadResourceString(&Dxskinsstrs::_sdxSkinParentNotFound)
extern DELPHI_PACKAGE System::ResourceString _sdxSkinsRootFolder;
#define Dxskinsstrs_sdxSkinsRootFolder System::LoadResourceString(&Dxskinsstrs::_sdxSkinsRootFolder)
#define sdxSkinBinaryProjectExt L".skinres"
#define sdxSkinVerticalSuffix L"Vert"
#define sdxResourceType L"DXSKINS"
#define sdxNavBarResourceType L"DXNAVBARSKINS"
#define sdxAdditionProperties L"AdditionalProperties"
#define sdxAlternateImage L"AlternateImage"
#define sdxColors L"Colors"
#define sdxDefaultColorPaletteName L"Default"
#define sdxColorPalette L"ColorPalette"
#define sdxColorPalettes L"ColorPalettes"
#define sdxDefaultGlyphColorPalettes L"DefaultGlyphColorPalettes"
#define sdxFontBold L"FontBold"
#define sdxFontSize L"FontSize"
#define sdxInteger L"Int"
#define sdxMinSize L"MinSize"
#define sdxOffset L"Offset"
#define sdxOffsetX L"OffsetX"
#define sdxOffsetY L"OffsetY"
#define sdxProperties L"Properties"
#define sdxValue L"Value"
#define sdxValueReferenceSuffix L"Reference"
#define sdxValueReference L"ValueReference"
#define sdxSkinGroupBars L"Bars"
#define sdxSkinGroupCommon L"Common"
#define sdxSkinGroupDetails L"Details"
#define sdxSkinGroupDocking L"Docking"
#define sdxSkinGroupEditors L"Editors"
#define sdxSkinGroupForm L"Form"
#define sdxSkinGroupGantt L"GanttControl"
#define sdxSkinGroupGrid L"Grid"
#define sdxSkinGroupHamburgerMenu L"HamburgerMenu"
#define sdxSkinGroupLayoutControl L"LayoutControl"
#define sdxSkinGroupListView L"ListView"
#define sdxSkinGroupMapControl L"MapControl"
#define sdxSkinGroupNavBar L"NavBar"
#define sdxSkinGroupNavPane L"NavPane"
#define sdxSkinGroupPDFViewer L"PDFViewer"
#define sdxSkinGroupPrintingSystem L"PrintingSystem"
#define sdxSkinGroupRibbon L"Ribbon"
#define sdxSkinGroupRichEdit L"RichEdit"
#define sdxSkinGroupScheduler L"Scheduler"
#define sdxSkinGroupTabs L"PageControl"
#define sdxSkinGroupTileControl L"TileControl"
#define sdxSkinGroupVGrid L"VerticalGrid"
#define sdxSchedulerSeparatorColor L"SeparatorColor"
#define sdxSkinsBarDisabledTextColor L"DisabledTextColor"
#define sdxSkinsContainerBorderColor L"ContainerBorderColor"
#define sdxSkinsContainerHighlightBorderColor L"ContainerHighlightBorderColor"
#define sdxSkinsContentColor L"ContentColor"
#define sdxSkinsContentEvenColor L"ContentEvenColor"
#define sdxSkinsContentOddColor L"ContentOddColor"
#define sdxSkinsContentTextColor L"ContentTextColor"
#define sdxSkinsHeaderBackgroundColor L"HeaderBackgroundColor"
#define sdxSkinsHeaderBackgroundTextColor L"HeaderBackgroundTextColor"
#define sdxSkinsSearchResultHighlightColor L"SearchResultHighlightColor"
#define sdxSkinsSearchResultHighlightTextColor L"SearchResultHighlightTextColor"
#define sdxSkinsInactiveColor L"InactiveColor"
#define sdxSkinsInactiveTextColor L"InactiveTextColor"
#define sdxSkinsLayoutControlColor L"LayoutControlColor"
#define sdxSkinsRadialMenuBackgroundColor L"RadialMenuBackgroundColor"
#define sdxSkinsRadialMenuBaseColor L"RadialMenuBaseColor"
#define sdxSkinsSchedulerNavigatorColor L"NavigatorColor"
#define sdxSkinsSelectionColor L"SelectionColor"
#define sdxSkinsSelectionTextColor L"SelectionTextColor"
#define sdxSkinsTabTextColor L"TabHeaderTextColor"
#define sdxSkinsTabTextColorActive L"TabHeaderTextColorActive"
#define sdxSkinsTabTextColorActiveHot L"TabHeaderTextColorActiveHot"
#define sdxSkinsTabTextColorDisabled L"TabHeaderTextColorDisabled"
#define sdxSkinsTabTextColorHot L"TabHeaderTextColorHot"
#define sdxSkinsPDFViewerFindPanel L"FindPanel"
#define sdxSkinsPDFViewerSelectionColor L"SelectionColor"
#define sdxSkinsPDFViewerNavigationPaneBackground L"NavigationPaneBackground"
#define sdxSkinsPDFViewerNavigationPaneButton L"NavigationPaneButton"
#define sdxSkinsPDFViewerNavigationPaneButtonArrow L"NavigationPaneButtonArrow"
#define sdxSkinsPDFViewerNavigationPaneButtonMinimized L"NavigationPaneButtonMinimized"
#define sdxSkinsPDFViewerNavigationPanePageBackground L"NavigationPanePageBackground"
#define sdxSkinsPDFViewerNavigationPanePageButton L"NavigationPanePageButton"
#define sdxSkinsPDFViewerNavigationPanePageCaption L"NavigationPanePageCaption"
#define sdxSkinsPDFViewerNavigationPaneSelectedPageExpandValue L"NavigationPaneSelectedPageExpandValue"
#define sdxSkinsPDFViewerNavigationPaneSelectedPageOverlapValue L"NavigationPaneSelectedPageOverlapValue"
#define sdxSkinsSpreadSheetContentColor L"SpreadSheetContentColor"
#define sdxSkinsSpreadSheetContentTextColor L"SpreadSheetContentTextColor"
#define sdxSkinsSpreadSheetFrozenPaneSeparatorColor L"SpreadSheetFrozenPaneSeparatorColor"
#define sdxSkinsSpreadSheetGroupLineColor L"SpreadSheetGroupLineColor"
#define sdxSkinsSpreadSheetSelectionColor L"SpreadSheetSelectionColor"
#define sdxSkinsGridLikeControlContentColor L"GridLikeControlContentColor"
#define sdxSkinsGridLikeControlContentEvenColor L"GridLikeControlContentEvenColor"
#define sdxSkinsGridLikeControlContentOddColor L"GridLikeControlContentOddColor"
#define sdxSkinsGridLikeControlContentTextColor L"GridLikeControlContentTextColor"
#define sdxSkinsGridLikeControlBackgroundColor L"GridLikeControlBackgroundColor"
#define sdxSkinsEditorBackgroundColor L"BackgroundColor"
#define sdxSkinsEditorBackgroundDisabledColor L"BackgroundDisabledColor"
#define sdxSkinsEditorBackgroundInactiveColor L"BackgroundInactiveColor"
#define sdxSkinsEditorBackgroundReadOnlyColor L"BackgroundReadOnlyColor"
#define sdxSkinsEditorTextColor L"TextColor"
#define sdxSkinsEditorTextDisabledColor L"TextDisabledColor"
#define sdxSkinsEditorTextInactiveColor L"TextInactiveColor"
#define sdxSkinsEditorTextReadOnlyColor L"TextReadOnlyColor"
#define sdxSkinsEditorHyperLinkTextColor L"HyperLinkTextColor"
#define sdxSkinsCalendarDayTextColor L"CalendarDayTextColor"
#define sdxSkinsCalendarHolidayTextColor L"CalendarHolidayTextColor"
#define sdxSkinsCalendarInactiveDayTextColor L"CalendarInactiveDayTextColor"
#define sdxSkinsCalendarNavigationButton L"CalendarNavigationButton"
#define sdxSkinsCalendarSelectedDayColor L"CalendarSelectedDayColor"
#define sdxSkinsCalendarSelectedDayTextColor L"CalendarSelectedDayTextColor"
#define sdxSkinsCalendarSeparatorColor L"CalendarSeparatorColor"
#define sdxSkinsCalendarTodayFrameColor L"CalendarTodayFrameColor"
#define sdxSkinsCalendarTodayTextColor L"CalendarTodayTextColor"
#define sdxSkinsCalendarWeekendDayTextColor L"CalendarWeekendDayTextColor"
#define sdxSkinsCalcEditDigitTextColor L"CalcEditDigitTextColor"
#define sdxSkinsCalcEditArithmeticOperationTextColor L"CalcEditArithmeticOperationTextColor"
#define sdxSkinsCalcEditEditingOperationTextColor L"CalcEditEditingOperationTextColor"
#define sdxSkinsCalcEditMemoryOperationTextColor L"CalcEditMemoryOperationTextColor"
#define sdxSkinsCalcEditScientificOperationTextColor L"CalcEditScientificOperationTextColor"
#define sdxBreadcrumbEditBackgroundColor L"BreadcrumbEditBackgroundColor"
#define sdxBreadcrumbEditBackgroundDisabledColor L"BreadcrumbEditBackgroundDisabledColor"
#define sdxBreadcrumbEditBackgroundFocusedColor L"BreadcrumbEditBackgroundFocusedColor"
#define sdxBreadcrumbEditBackgroundHotColor L"BreadcrumbEditBackgroundHotColor"
#define sdxBreadcrumbEditBorderColor L"BreadcrumbEditBorderColor"
#define sdxBreadcrumbEditBorderDisabledColor L"BreadcrumbEditBorderDisabledColor"
#define sdxBreadcrumbEditBorderFocusedColor L"BreadcrumbEditBorderFocusedColor"
#define sdxBreadcrumbEditBorderHotColor L"BreadcrumbEditBorderHotColor"
#define sdxListViewGroup L"Group"
#define sdxListViewGroupExpandButton L"GroupExpandButton"
#define sdxListViewGroupLine L"GroupLine"
#define sdxListViewIcon L"Icon"
#define sdxListViewItem L"Item"
#define sdxBevelShapeColor1 L"BevelShapeColor1"
#define sdxBevelShapeColor2 L"BevelShapeColor2"
#define sdxComboButtonGlyph L"ComboButtonGlyph"
#define sdxSpinUpGlyph L"SpinUpGlyph"
#define sdxSpinDownGlyph L"SpinDownGlyph"
#define sdxSpinLeftGlyph L"SpinLeftGlyph"
#define sdxSpinRightGlyph L"SpinRightGlyph"
#define sdxEditorButton L"EditorButton"
#define sdxSearchButtonGlyph L"SearchButtonGlyph"
#define sdxEditorButtonMergeBorders L"MergeBorders"
#define sdxCloseButton L"CloseButton"
#define sdxSliderArrowBottom L"SliderArrowBottom"
#define sdxSliderArrowLeft L"SliderArrowLeft"
#define sdxSliderArrowRight L"SliderArrowRight"
#define sdxSliderArrowTop L"SliderArrowTop"
#define sdxSupportsNavigationControlExtensionToFormCaption L"SupportsNavigationControlExtensionToFormCaption"
#define sdxCaptionFontDelta L"FontDelta"
#define sdxCaptionFontBold L"FontBold"
#define sdxLoadingBig L"LoadingBig"
#define sdxBarsBar L"Bar"
#define sdxBarsBarCustomize L"BarCustomize"
#define sdxBarsBarCustomizeVertical L"BarCustomizeVertical"
#define sdxBarsBarFinger L"BarDragGrip"
#define sdxBarsBarFingerVertical L"BarDragGripVertical"
#define sdxBarsBarSeparator L"BarSeparator"
#define sdxBarsBarVertical L"BarVertical"
#define sdxBarsBarVerticalSeparator L"BarSeparatorVertical"
#define sdxBarsDock L"Dock"
#define sdxBarsFloatBar L"FloatBar"
#define sdxBarsItemSeparator L"ItemSeparator"
#define sdxBarsLinkSelected L"LinkSelected"
#define sdxBarsLinkStatic L"LinkStatic"
#define sdxBarsMainMenu L"MainMenu"
#define sdxBarsMainMenuCustomize L"MainMenuCustomize"
#define sdxBarsMainMenuDrag L"MainMenuDrag"
#define sdxBarsMainMenuLinkSelected L"MainMenuLinkSelected"
#define sdxBarsMainMenuVertical L"MainMenuVertical"
#define sdxBarsMDIButtonClose L"MDIButtonClose"
#define sdxBarsMDIButtonMinimize L"MDIButtonMinimize"
#define sdxBarsMDIButtonRestore L"MDIButtonRestore"
#define sdxBarsPopupMenu L"PopupMenu"
#define sdxBarsPopupMenuCheck L"PopupMenuCheck"
#define sdxBarsPopupMenuDropDownButtonArrow L"PopupMenuDropDownButtonArrow"
#define sdxBarsPopupMenuDropDownButtonLabel L"PopupMenuDropDownButtonLabel"
#define sdxBarsPopupMenuExpandButton L"PopupMenuExpandButton"
#define sdxBarsPopupMenuLinkSelected L"PopupMenuLinkSelected"
#define sdxBarsPopupMenuSeparator L"PopupMenuSeparator"
#define sdxBarsPopupMenuSideStrip L"PopupMenuSideStrip"
#define sdxBarsPopupMenuSideStripNonRecent L"PopupMenuSideStripNonRecent"
#define sdxLabelLine L"LabelLine"
#define sdxLabelLineVert L"LabelLineVert"
#define sdxGalleryBackground L"GalleryBackground"
#define sdxGalleryGroup L"GalleryGroup"
#define sdxGalleryItem L"GalleryItem"
#define sdxGalleryItemGlyphFrame L"GalleryItemGlyphFrame"
#define sdxDescriptionTextColorPrefix L"Description"
#define sdxTextColorDisabled L"TextColorDisabled"
#define sdxTextColorDisabledLegacy L"DisabledText"
#define sdxTextColorHot L"TextColorHot"
#define sdxTextColorInactive L"TextColorInactive"
#define sdxTextColorNormal L"TextColor"
#define sdxTextColorPressed L"TextColorPressed"
#define sdxTextColorSelected L"TextColorSelected"
#define sdxTextColorSelectedHot L"TextColorSelectedHot"
#define sdxTextGlowColor L"TextGlowColor"
#define sdxCommonCriticalColor L"Critical"
#define sdxCommonHotTrackedColor L"HotTrackedColor"
#define sdxCommonHotTrackedTextColor L"HotTrackedTextColor"
#define sdxCommonInformationColor L"Information"
#define sdxCommonQuestionColor L"Question"
#define sdxBreadcrumbEditButton L"BreadcrumbEditButton"
#define sdxBreadcrumbEditButtonsAreaSeparator L"BreadcrumbEditButtonsAreaSeparator"
#define sdxBreadcrumbEditDropDownButton L"BreadcrumbEditDropDownButton"
#define sdxBreadcrumbEditNodeButton L"BreadcrumbEditNodeButton"
#define sdxBreadcrumbEditNodeSplitButtonLeft L"BreadcrumbEditNodeSplitButtonLeft"
#define sdxBreadcrumbEditNodeSplitButtonRight L"BreadcrumbEditNodeSplitButtonRight"
#define sdxBreadcrumbEditProgressChunk L"BreadcrumbEditProgressChunk"
#define sdxBreadcrumbEditProgressChunkOverlay L"BreadcrumbEditProgressChunkOverlay"
#define sdxBreadcrumbEditProgressChunkPadding L"BreadcrumbEditProgressChunkPadding"
#define sdxLayoutViewRecord L"LayoutViewRecord"
#define sdxLayoutViewRecordBottom L"LayoutViewRecordBottom"
#define sdxLayoutViewRecordLeft L"LayoutViewRecordLeft"
#define sdxLayoutViewRecordRight L"LayoutViewRecordRight"
#define sdxLayoutViewRecordTop L"LayoutViewRecordTop"
#define sdxLayoutViewRecordCaptionBottom L"LayoutViewRecordCaptionBottom"
#define sdxLayoutViewRecordCaptionLeft L"LayoutViewRecordCaptionLeft"
#define sdxLayoutViewRecordCaptionRight L"LayoutViewRecordCaptionRight"
#define sdxLayoutViewRecordCaptionTop L"LayoutViewRecordCaptionTop"
#define sdxLayoutViewRecordExpandButton L"LayoutViewRecordExpandButton"
#define sdxLayoutViewGroupPadding L"LayoutViewGroupPadding"
#define sdxLayoutViewGroupSpacing L"LayoutViewGroupSpacing"
#define sdxLayoutViewGroupWithoutBordersPadding L"LayoutViewGroupWithoutBordersPadding"
#define sdxLayoutViewGroupWithoutBordersSpacing L"LayoutViewGroupWithoutBordersSpacing"
#define sdxLayoutViewItem L"LayoutViewItem"
#define sdxLayoutViewItemPadding L"LayoutViewItemPadding"
#define sdxLayoutViewItemSpacing L"LayoutViewItemSpacing"
#define sdxLayoutViewRootGroupPadding L"LayoutViewRootGroupPadding"
#define sdxLayoutViewRootGroupSpacing L"LayoutViewRootGroupSpacing"
#define sdxLayoutViewRootGroupWithoutBordersPadding L"LayoutViewRootGroupWithoutBordersPadding"
#define sdxLayoutViewRootGroupWithoutBordersSpacing L"LayoutViewRootGroupWithoutBordersSpacing"
#define sdxLayoutViewTabbedGroupPadding L"LayoutViewTabbedGroupPadding"
#define sdxLayoutViewTabbedGroupSpacing L"LayoutViewTabbedGroupSpacing"
#define sdxToggleSwitch L"ToggleSwitch"
#define sdxToggleSwitchThumb L"ToggleSwitchThumb"
#define sdxToggleSwitchTextMargin L"TextMargin"
#define sdxGaugeBackground L"GaugeBackground"
#define sdxAlertWindow L"AlertWindow"
#define sdxAlertWindowButton L"AlertWindowButton"
#define sdxAlertWindowButtonGlyphs L"AlertWindowButtonGlyphs"
#define sdxAlertWindowCaption L"AlertWindowCaption"
#define sdxAlertWindowCornerRadius L"CornerRadius"
#define sdxAlertWindowNavigationPanel L"AlertWindowNavigationPanel"
#define sdxAlertWindowNavigationPanelButton L"AlertWindowNavigationPanelButton"
#define sdxRatingIndicator L"RatingIndicator"
#define sdxRibbonAppButtonLeftIndent L"LeftIndent"
#define sdxRibbonAppButtonRightIndent L"RightIndent"
#define sdxRibbonApplicationButton L"FormAppButton"
#define sdxRibbonApplicationButton2010 L"FormAppButton2010"
#define sdxRibbonAppMenuBackground L"AppMenuBackground"
#define sdxRibbonAppMenuFooterBackground L"AppMenuBackgroundBottom"
#define sdxRibbonAppMenuHeaderBackground L"AppMenuBackgroundTop"
#define sdxRibbonBackstageViewBackButton L"BackstageViewBackButton"
#define sdxRibbonBackstageViewBackground L"BackstageViewBackground"
#define sdxRibbonBackstageViewImage L"BackstageViewImage"
#define sdxRibbonBackstageViewMenuBackground L"BackstageViewMenuBackground"
#define sdxRibbonBackstageViewMenuButton L"BackstageViewMenuButton"
#define sdxRibbonBackstageViewMenuHeader L"BackstageViewMenuHeader"
#define sdxRibbonBackstageViewMenuSeparator L"BackstageViewMenuSeparator"
#define sdxRibbonBackstageViewTabHeader L"BackstageViewTabHeader"
#define sdxRibbonBackstageViewTabHeaderArrow L"BackstageViewTabHeaderArrow"
#define sdxRibbonButtonArrow L"ButtonArrow"
#define sdxRibbonButtonDisabledText L"ButtonDisabled"
#define sdxRibbonButtonGroup L"ButtonGroup"
#define sdxRibbonButtonGroupButton L"ButtonGroupButton"
#define sdxRibbonButtonGroupSeparator L"ButtonGroupSeparator"
#define sdxRibbonButtonGroupSplitButtonLeft L"ButtonGroupSplitButtonLeft"
#define sdxRibbonButtonGroupSplitButtonRight L"ButtonGroupSplitButtonRight"
#define sdxRibbonCaptionFontDelta L"FontDelta"
#define sdxRibbonCollapsedToolBarBackground L"TabGroupCollapsed"
#define sdxRibbonCollapsedToolBarGlyphBackground L"TabGroupCollapsedBox"
#define sdxRibbonContextualTabHeader L"ContextualTabHeader"
#define sdxRibbonContextualTabLabel L"ContextualTabLabel"
#define sdxRibbonContextualTabLabelOnGlass L"ContextualTabLabelOnGlass"
#define sdxRibbonContextualTabPanel L"ContextualTabPanel"
#define sdxRibbonContextualTabSeparator L"ContextualTabSeparator"
#define sdxRibbonDialogFrameBottom L"DialogFrameBottom"
#define sdxRibbonDialogFrameLeft L"DialogFrameLeft"
#define sdxRibbonDialogFrameRight L"DialogFrameRight"
#define sdxRibbonDocumentNameTextColor L"DocumentNameTextColor"
#define sdxRibbonEditorBackground L"EditorBackground"
#define sdxRibbonExtraPaneButton L"AppMenuExtraPaneButton"
#define sdxRibbonExtraPaneColor L"AppMenuExtraPaneColor"
#define sdxRibbonExtraPaneHeaderSeparator L"AppMenuExtraPaneHeaderSeparator"
#define sdxRibbonExtraPanePinButtonGlyph L"AppMenuExtraPanePinButtonGlyph"
#define sdxRibbonFormBottom L"FormFrameBottom"
#define sdxRibbonFormButtonAutoHideModeShowUI L"FormButtonAutoHideModeShowUI"
#define sdxRibbonFormButtonDisplayOptions L"FormButtonDisplayOptions"
#define sdxRibbonFormCaption L"FormCaption"
#define sdxRibbonFormCaptionRibbonHidden L"FormCaptionRibbonHidden"
#define sdxRibbonFormContent L"FormContent"
#define sdxRibbonFormFrameLeft L"FormFrameLeft"
#define sdxRibbonFormFrameRight L"FormFrameRight"
#define sdxRibbonUseRoundedWindowCorners L"UseRoundedWindowCorners"
#define sdxRibbonGalleryBackground L"DropDownGalleryBackground"
#define sdxRibbonGalleryButtonDown L"InRibbonGalleryButtonDown"
#define sdxRibbonGalleryButtonDropDown L"InRibbonGalleryButtonDropDown"
#define sdxRibbonGalleryButtonUp L"InRibbonGalleryButtonUp"
#define sdxRibbonGalleryGroupCaption L"DropDownGalleryGroupHeader"
#define sdxRibbonGalleryPane L"InRibbonGalleryPane"
#define sdxRibbonGallerySizeGrips L"DropDownGallerySizeGrip"
#define sdxRibbonGallerySizingPanel L"DropDownGallerySizePanel"
#define sdxRibbonHeaderBackground L"TabBackground"
#define sdxRibbonHeaderBackgroundOnGlass L"TabBackgroundOnGlass"
#define sdxRibbonKeyTip L"KeyTip"
#define sdxRibbonLargeButton L"LargeButton"
#define sdxRibbonLargeSplitButtonBottom L"LargeSplitButtonBottom"
#define sdxRibbonLargeSplitButtonTop L"LargeSplitButtonTop"
#define sdxRibbonMinimizeButtonGlyph L"MinimizeButtonGlyph"
#define sdxRibbonQATCustomizeButtonOutsideQAT L"DisplayCustomizeButtonOutsideQAT"
#define sdxRibbonQATIndentBeforeCustomizeItem L"IndentBeforeCustomizeButton"
#define sdxRibbonQuickAccessToolbarOffset L"Offset"
#define sdxRibbonQuickToolbarAbove L"QATAboveBackground"
#define sdxRibbonQuickToolbarBelow L"QATBelowBackground"
#define sdxRibbonQuickToolbarButtonGlyph L"QATButtonGlyph"
#define sdxRibbonQuickToolbarDropDown L"QATOverflow"
#define sdxRibbonQuickToolbarGlyph L"QATCustomizeButton"
#define sdxRibbonQuickToolbarInCaption L"QATInRibbonBackground"
#define sdxRibbonSmallButton L"Button"
#define sdxRibbonSpaceBetweenTabGroups L"SpaceBetweenTabGroups"
#define sdxRibbonSplitButtonLeft L"SplitButtonLeft"
#define sdxRibbonSplitButtonRight L"SplitButtonRight"
#define sdxRibbonStatusBarBackground L"StatusBarBackground"
#define sdxRibbonStatusBarButton L"StatusBarButton"
#define sdxRibbonStatusBarSeparator L"StatusBarSeparator"
#define sdxRibbonTabAeroSupport L"TabAeroSupport"
#define sdxRibbonTabGroup L"TabGroup"
#define sdxRibbonTabGroupHeader L"TabGroupCaption"
#define sdxRibbonTabGroupItemsSeparator L"TabGroupItemsSeparator"
#define sdxRibbonTabGroupLeftScroll L"TabGroupLeftScrollButton"
#define sdxRibbonTabGroupRightScroll L"TabGroupRightScrollButton"
#define sdxRibbonTabHeaderDownGrowIndent L"TabHeaderDownGrow"
#define sdxRibbonTabHeaderPage L"Tab"
#define sdxRibbonTabPanel L"TabPanel"
#define sdxRibbonTabPanelBottomIndent L"BottomIndent"
#define sdxRibbonTabPanelGroupButton L"TabGroupButton"
#define sdxRibbonTabSeparatorLine L"TabSeparatorLine"
#define sdxNavBarAccordionControlBackground L"AccordionControlBackground"
#define sdxNavBarAccordionControlChildItemOffset L"ChildItemOffset"
#define sdxNavBarAccordionControlContentContainerPadding L"ContentContainerPadding"
#define sdxNavBarAccordionControlDistanceBetweenRootGroups L"DistanceBetweenRootGroups"
#define sdxNavBarAccordionControlGlyphToTextIndent L"GlyphToTextIndent"
#define sdxNavBarAccordionControlGroup L"AccordionControlGroup"
#define sdxNavBarAccordionControlGroupCloseButton L"AccordionControlGroupCloseButton"
#define sdxNavBarAccordionControlGroupOpenButton L"AccordionControlGroupOpenButton"
#define sdxNavBarAccordionControlItem L"AccordionControlItem"
#define sdxNavBarAccordionControlRootGroup L"AccordionControlRootGroup"
#define sdxNavBarAccordionControlRootGroupCloseButton L"AccordionControlRootGroupCloseButton"
#define sdxNavBarAccordionControlRootGroupOpenButton L"AccordionControlRootGroupOpenButton"
#define sdxNavBarAccordionControlSearchButton L"AccordionControlSearchButton"
#define sdxNavBarBackground L"Background"
#define sdxNavBarGroupClient L"GroupClient"
#define sdxNavBarGroupCloseButton L"GroupCloseButton"
#define sdxNavBarGroupFooter L"GroupFooter"
#define sdxNavBarGroupHeader L"GroupHeader"
#define sdxNavBarGroupOpenButton L"GroupOpenButton"
#define sdxNavBarItem L"Item"
#define sdxNavPaneCaptionHeight L"Height"
#define sdxNavPaneCollapseButton L"CollapseButton"
#define sdxNavPaneCollapsedGroupClient L"CollapsedGroupClient"
#define sdxNavPaneExpandButton L"ExpandButton"
#define sdxNavPaneFormBorder L"PopupBorder"
#define sdxNavPaneFormSizeGrip L"PopupSizeGrip"
#define sdxNavPaneGroupButton L"GroupButton"
#define sdxNavPaneGroupButtonSelected L"GroupButtonSelected"
#define sdxNavPaneGroupCaption L"Caption"
#define sdxNavPaneGroupClient L"GroupClient"
#define sdxNavPaneItem L"Item"
#define sdxNavPaneItemSelected L"ItemSelected"
#define sdxNavPaneOfficeNavigationBar L"OfficeNavigationBar"
#define sdxNavPaneOfficeNavigationBarItem L"OfficeNavigationBarItem"
#define sdxNavPaneOfficeNavigationBarSkinningItem L"OfficeNavigationBarSkinningItem"
#define sdxNavPaneOffsetGroupBorders L"OverlapGroupBorders"
#define sdxNavPaneOverflowPanel L"OverflowPanel"
#define sdxNavPaneOverflowPanelExpandItem L"OverflowPanelExpandItem"
#define sdxNavPaneOverflowPanelItem L"OverflowPanelItem"
#define sdxNavPaneScrollDownBtn L"ScrollDownButton"
#define sdxNavPaneScrollUpBtn L"ScrollUpButton"
#define sdxNavPaneSplitter L"Splitter"
#define sdxSchedulerAllDayArea L"AllDayArea"
#define sdxSchedulerAllDayAreaSelected L"AllDayAreaSelected"
#define sdxSchedulerAppointment L"Appointment"
#define sdxSchedulerAppointmentBorder L"AppointmentBorder"
#define sdxSchedulerAppointmentBorderColor L"BorderColor"
#define sdxSchedulerAppointmentBorderSize L"BorderSize"
#define sdxSchedulerAppointmentBottomShadow L"AppointmentBottomShadow"
#define sdxSchedulerAppointmentMask L"AppointmentMask"
#define sdxSchedulerAppointmentRight L"AppointmentRightBorder"
#define sdxSchedulerAppointmentRightShadow L"AppointmentRightShadow"
#define sdxSchedulerCurrentTimeIndicator L"CurrentTimeIndicator"
#define sdxSchedulerGroup L"Group"
#define sdxSchedulerLabelCircle L"LabelCircle"
#define sdxSchedulerTaskExpandButton L"TaskExpandButton"
#define sdxSchedulerMilestone L"Milestone"
#define sdxSchedulerMoreButton L"MoreButton"
#define sdxSchedulerNavButtonNext L"NavButtonNext"
#define sdxSchedulerNavButtonNextArrow L"NavButtonNextArrow"
#define sdxSchedulerNavButtonPrev L"NavButtonPrev"
#define sdxSchedulerNavButtonPrevArrow L"NavButtonPrevArrow"
#define sdxSchedulerResourceColor L"ResourceColor%0.2d"
#define sdxSchedulerTimeGridCurrentTimeIndicator L"TimeGridCurrentTimeIndicator"
#define sdxSchedulerTimeGridHeader L"TimeGridHeader"
#define sdxSchedulerTimeGridHeaderSelected L"TimeGridHeaderSelected"
#define sdxSchedulerTimeLine L"DefaultTimeLine"
#define sdxSchedulerTimeRuler L"Ruler"
#define sdxDCActiveTabHeaderDownGrow L"ActiveTabHeaderDownGrow"
#define sdxDCActiveTabHeaderHGrow L"ActiveTabHeaderHGrow"
#define sdxDCActiveTabHeaderUpGrow L"ActiveTabHeaderUpGrow"
#define sdxDockCtrlAutoHideBar L"AutoHideBar"
#define sdxDockCtrlAutoHideBarBottom L"AutoHideBarBottom"
#define sdxDockCtrlAutoHideBarLeft L"AutoHideBarLeft"
#define sdxDockCtrlAutoHideBarRight L"AutoHideBarRight"
#define sdxDockCtrlBorder L"DockWindowBorder"
#define sdxDockCtrlCaption L"DockWindowCaption"
#define sdxDockCtrlInactiveCaptionTextColor L"InactiveCaptionTextColor"
#define sdxDockCtrlHiddenBarTextColor L"HiddenBarTextColor"
#define sdxDockCtrlHiddenBarTextHotColor L"HiddenBarTextHotColor"
#define sdxDockCtrlTabButtonHorz L"TabButtonHorz"
#define sdxDockCtrlTabButtonVert L"TabButtonVert"
#define sdxDockCtrlTabHeader L"TabHeader"
#define sdxDockCtrlTabHeaderAutoHideBar L"TabHeaderAutoHideBar"
#define sdxDockCtrlTabHeaderBackground L"TabHeaderBackground"
#define sdxDockCtrlTabHeaderCloseButton L"TabHeaderCloseButton"
#define sdxDockCtrlTabHeaderLine L"TabHeaderLine"
#define sdxDockCtrlWindowButton L"DockWindowButton"
#define sdxDockCtrlWindowGlyphs L"DockWindowButtonGlyphs"
#define sdxDockSiteContentColor L"DockSiteContentColor"
#define sdxGroupButton L"GroupButton"
#define sdxGroupButtonExpandGlyph L"GroupButtonExpandGlyph"
#define sdxGroupPanel L"GroupPanel"
#define sdxGroupPanelBottom L"GroupPanelBottom"
#define sdxGroupPanelCaptionBottom L"GroupPanelCaptionBottom"
#define sdxGroupPanelCaptionLeft L"GroupPanelCaptionLeft"
#define sdxGroupPanelCaptionRight L"GroupPanelCaptionRight"
#define sdxGroupPanelCaptionTailSize L"TailSize"
#define sdxGroupPanelCaptionTextPadding L"TextPadding"
#define sdxGroupPanelCaptionTop L"GroupPanelCaptionTop"
#define sdxGroupPanelLeft L"GroupPanelLeft"
#define sdxGroupPanelNoBorder L"GroupPanelNoBorder"
#define sdxGroupPanelRight L"GroupPanelRight"
#define sdxGroupPanelTop L"GroupPanelTop"
#define sdxBackButton L"BackButton"
#define sdxButton L"Button"
#define sdxCheckbox L"Checkbox"
#define sdxClearButton L"ClearButton"
#define sdxClock L"ClockFace"
#define sdxClockGlass L"ClockGlass"
#define sdxDropDownButtonLeft L"DropDownButtonLeft"
#define sdxDropDownButtonRight L"DropDownButtonRight"
#define sdxHighlightedItem L"HighlightedItem"
#define sdxNavigatorButton L"NavigatorButton"
#define sdxNavigatorGlyphs L"Navigator"
#define sdxNavigatorGlyphsVert L"NavigatorVert"
#define sdxNavigatorInfoPanel L"NavigatorInfoPanel"
#define sdxRadioButton L"RadioButton"
#define sdxScreenTipItem L"ScreenTipItem"
#define sdxScreenTipSeparator L"ScreenTipSeparator"
#define sdxScreenTipTitleItem L"ScreenTipTitleItem"
#define sdxScreenTipWindow L"ScreenTipWindow"
#define sdxScrollButton L"ScrollButton"
#define sdxScrollContentHorz L"ScrollContentHorz"
#define sdxScrollContentVert L"ScrollContentVert"
#define sdxScrollThumbButtonHorz L"ScrollThumbHorz"
#define sdxScrollThumbButtonVert L"ScrollThumbVert"
#define sdxSizeGrip L"SizeGrip"
#define sdxSplitterHorz L"SplitterHorz"
#define sdxSplitterVert L"Splitter"
#define sdxZoomInButton L"ZoomInButton"
#define sdxZoomOutButton L"ZoomOutButton"
#define sdxProgressBorder L"ProgressBorder"
#define sdxProgressChunk L"ProgressChunk"
#define sdxProgressOverloadBar L"ProgressOverloadBar"
#define sdxProgressPeakBar L"ProgressPeakBar"
#define sdxTrackBarThumb L"TrackBarThumb"
#define sdxTrackBarThumbBoth L"TrackBarThumbBoth"
#define sdxTrackBarThumbUp L"TrackBarThumbUp"
#define sdxTrackBarThumbVert L"TrackBarThumbVert"
#define sdxTrackBarThumbVertBoth L"TrackBarThumbVertBoth"
#define sdxTrackBarThumbVertUp L"TrackBarThumbVertUp"
#define sdxTrackBarTickColor L"TrackBarTickColor"
#define sdxTrackBarTrack L"TrackBarTrack"
#define sdxTrackBarTrackVert L"TrackBarTrackVert"
#define sdxRangeTrackBarThumbBoth L"RangeTrackBarThumbBoth"
#define sdxRangeTrackBarThumbLeft L"RangeTrackBarThumbLeft"
#define sdxRangeTrackBarThumbRight L"RangeTrackBarThumbRight"
#define sdxMapControlBackColor L"MapBackColor"
#define sdxMapControlBorderColor L"BorderColor"
#define sdxMapControlBorderWidth L"BorderWidth"
#define sdxMapControlCallout L"Callout"
#define sdxMapControlCalloutPointerHeight L"PointerHeight"
#define sdxMapControlCalloutPointerX L"PointerX"
#define sdxMapControlCalloutPointerY L"PointerY"
#define sdxMapControlCustomElement L"CustomElement"
#define sdxMapControlPushpin L"Pushpin"
#define sdxMapControlPushpinTextOriginX L"TextOriginX"
#define sdxMapControlPushpinTextOriginY L"TextOriginY"
#define sdxMapControlSelectedRegion L"SelectedRegion"
#define sdxMapControlShape L"Shape"
#define sdxMapControlPanelBackColor L"PanelBackColor"
#define sdxMapControlPanelBackColorAlpha L"PanelBackColorAlpha"
#define sdxMapControlPanelHotTrackedTextColor L"PanelHotTrackedTextColor"
#define sdxMapControlPanelPressedTextColor L"PanelPressedTextColor"
#define sdxMapControlPanelPressedTextColorAlpha L"PanelPressedTextColorAlpha"
#define sdxMapControlPanelTextColor L"PanelTextColor"
#define sdxPageControlButton L"TabButton"
#define sdxPageControlHeader L"TabHeader"
#define sdxPageControlHeaderButton L"TabHeaderButton"
#define sdxPageControlHeaderCloseButton L"TabHeaderCloseButton"
#define sdxPageControlHorz L"TabButtonHorz"
#define sdxPageControlPane L"TabPane"
#define sdxPageControlVert L"TabButtonVert"
#define sdxHeaderDownGrow L"HeaderDownGrow"
#define sdxHeaderDownGrowBottomRight L"HeaderDownGrowBottomRight"
#define sdxRowIndentFar L"RowIndentFar"
#define sdxRowIndentNear L"RowIndentNear"
#define sdxSelectedHeaderDownGrow L"SelectedHeaderDownGrow"
#define sdxSelectedHeaderDownGrowBottomRight L"SelectedHeaderDownGrowBottomRight"
#define sdxSelectedHeaderHGrow L"SelectedHeaderHGrow"
#define sdxSelectedHeaderUpGrow L"SelectedHeaderUpGrow"
#define sdxSortGlyphs L"SortShape"
#define sdxTileControlActionBar L"ActionBar"
#define sdxTileControlBackground L"Background"
#define sdxTileControlGroupCaption L"GroupCaption"
#define sdxTileControlItem L"Item"
#define sdxTileControlItemCheck L"ItemCheck"
#define sdxTileControlSelectionFocusedColor L"SelectionFocusedColor"
#define sdxTileControlSelectionHotColor L"SelectionHotColor"
#define sdxTileControlTabHeader L"TabHeader"
#define sdxTileControlTitle L"Title"
#define sdxTileControlVirtualGroup L"VirtualGroup"
#define sdxCardSeparator L"CardSeparator"
#define sdxFilterButton L"FilterButton"
#define sdxFilterButtonActive L"FilterButtonActive"
#define sdxFilterPanel L"GridFilterPanel"
#define sdxFooterCell L"FooterCell"
#define sdxFooterPanel L"FooterPanel"
#define sdxGridFixedColumnHighlightColor L"FixedColumnHighlightColor"
#define sdxGridFixedLine L"GridFixedLine"
#define sdxGridGroupRowStyleOffice11ContentColor L"Office11ContentColor"
#define sdxGridGroupRowStyleOffice11SeparatorColor L"Office11SeparatorColor"
#define sdxGridGroupRowStyleOffice11TextColor L"Office11TextColor"
#define sdxGridLine L"GridLine"
#define sdxGridWinExplorerViewGroup L"WinExplorerViewGroup"
#define sdxGridWinExplorerViewGroupCaptionLine L"WinExplorerViewGroupCaptionLine"
#define sdxGridWinExplorerViewGroupExpandButton L"WinExplorerViewGroupExpandButton"
#define sdxGridWinExplorerViewRecord L"WinExplorerViewRecord"
#define sdxGroupByBox L"GridGroupPanel"
#define sdxGroupByBoxLineColor L"LineColor"
#define sdxGroupRow L"GroupRow"
#define sdxHeader L"Header"
#define sdxHeaderLeft L"HeaderLeft"
#define sdxHeaderRight L"HeaderRight"
#define sdxHeaderSpecial L"HeaderSpecial"
#define sdxIndicatorImages L"IndicatorImages"
#define sdxSmartFilterButton L"SmartFilterButton"
#define sdxTreeListGridLineColor L"TreeListGridLineColor"
#define sdxTreeListTreeLineColor L"TreeListTreeLineColor"
#define sdxPlusMinus L"PlusMinus"
#define sdxPlusMinusEx L"PlusMinusEx"
#define sdxVGridBandLine L"BandBorder"
#define sdxVGridLine L"GridLine"
#define sdxVGridRowHeader L"RowHeader"
#define sdxVGridCategory L"Category"
#define sdxTextShadowColor L"TextShadowColor"
#define sdxFormFrameLeft L"FormFrameLeft"
#define sdxFormCaption L"FormCaption"
#define sdxFormContent L"FormContent"
#define sdxFormFrameRight L"FormFrameRight"
#define sdxFormFrameBottom L"FormFrameBottom"
#define sdxSmallFormFrameLeft L"SmallFormFrameLeft"
#define sdxSmallFormCaption L"SmallFormCaption"
#define sdxSmallFormFrameRight L"SmallFormFrameRight"
#define sdxSmallFormFrameBottom L"SmallFormFrameBottom"
#define sdxFormButtonClose L"FormButtonClose"
#define sdxFormButtonHelp L"FormButtonHelp"
#define sdxFormButtonMaximize L"FormButtonMaximize"
#define sdxFormButtonMinimize L"FormButtonMinimize"
#define sdxFormButtonRestore L"FormButtonRestore"
#define sdxSmallFormButtonClose L"SmallFormButtonClose"
#define sdxStatusBar L"StatusBar"
#define sdxPrintingSystemPageBorder L"PageBorder"
#define sdxPrintingSystemPreviewBackground L"PreviewBackground"
#define sdxRichEditCornerPanel L"CornerPanel"
#define sdxRichEditRulerBackgroundHorz L"RulerBackgroundHorz"
#define sdxRichEditRulerBackgroundVert L"RulerBackgroundVert"
#define sdxRichEditRulerColumnResizer L"RulerColumnResizer"
#define sdxRichEditRulerDefaultTabColor L"RulerDefaultTabColor"
#define sdxRichEditRulerIndent L"RulerIndent"
#define sdxRichEditRulerIndentBottom L"RulerIndentBottom"
#define sdxRichEditRulerLargeTick L"RulerLargeTick"
#define sdxRichEditRulerRightMargin L"RulerRightMargin"
#define sdxRichEditRulerSection L"RulerSection"
#define sdxRichEditRulerSmallTick L"RulerSmallTick"
#define sdxRichEditRulerTab L"RulerTab"
#define sdxRichEditRulerTabTypeBackground L"RulerTabTypeBackground"
#define sdxRichEditRulerTextColor L"RulerTextColor"
#define sdxRangeControlBorder L"RangeControlBorder"
#define sdxRangeControlLeftThumb L"RangeControlLeftThumb"
#define sdxRangeControlRightThumb L"RangeControlRightThumb"
#define sdxRangeControlRulerHeader L"RangeControlRulerHeader"
#define sdxRangeControlSizingGlyph L"RangeControlSizingGlyph"
#define sdxRangeControlDefaultElementColor L"DefaultElementColor"
#define sdxRangeControlBackColor L"BackColor"
#define sdxRangeControlInnerBorderColor L"InnerBorderColor"
#define sdxRangeControlElementBaseColor L"ElementBaseColor"
#define sdxRangeControlElementForeColor L"ElementForeColor"
#define sdxRangeControlElementFontSize L"ElementFontSize"
#define sdxRangeControlLabelColor L"LabelColor"
#define sdxRangeControlOutOfRangeColorMask L"OutOfRangeColorMask"
#define sdxRangeControlRangePreviewColor L"RangePreviewColor"
#define sdxRangeControlRuleColor L"RuleColor"
#define sdxRangeControlScrollAreaColor L"ScrollAreaColor"
#define sdxRangeControlScrollAreaHeight L"ScrollAreaHeight"
#define sdxRangeControlViewPortPreviewColor L"ViewPortPreviewColor"
#define sdxRangeControlSelectionBorderColor L"SelectionBorderColor"
#define sdxRangeControlSelectionColor L"SelectionColor"
#define sdxHamburgerMenuBackground L"Background"
#define sdxHamburgerMenuChildGroup L"ChildGroup"
#define sdxHamburgerMenuChildGroupCloseButton L"ChildGroupCloseButton"
#define sdxHamburgerMenuChildGroupOpenButton L"ChildGroupOpenButton"
#define sdxHamburgerMenuChildItemOffset L"ChildItemOffset"
#define sdxHamburgerMenuDistanceBetweenGroups L"DistanceBetweenGroups"
#define sdxHamburgerMenuGroup L"Group"
#define sdxHamburgerMenuGroupCloseButton L"GroupCloseButton"
#define sdxHamburgerMenuGroupOpenButton L"GroupOpenButton"
#define sdxHamburgerMenuHamburgerButton L"HamburgerButton"
#define sdxHamburgerMenuItem L"Item"
#define sdxHamburgerMenuNavPaneBackground L"NavPaneBackground"
#define sdxHamburgerMenuNavPaneExpandButton L"NavPaneExpandButton"
#define sdxHamburgerMenuNavPaneItem L"NavPaneItem"
#define sdxHamburgerMenuNavPaneItemSelected L"NavPaneItemSelected"
#define sdxHamburgerMenuScrollDownButton L"ScrollDownButton"
#define sdxHamburgerMenuScrollUpButton L"ScrollUpButton"
#define sdxGanttDependencyEditPointLeft L"DependencyEditPointLeft"
#define sdxGanttDependencyEditPointRight L"DependencyEditPointRight"
#define sdxGanttFocusedRow L"FocusedRow"
#define sdxGanttMilestone L"Milestone"
#define sdxGanttMilestoneBaseline L"MilestoneBaseline"
#define sdxGanttSummaryTask L"SummaryTask"
#define sdxGanttSummaryTaskBaseline L"SummaryTaskBaseline"
#define sdxGanttSummaryTaskProgress L"SummaryTaskProgress"
#define sdxGanttTask L"Task"
#define sdxGanttTaskProgress L"TaskProgress"
#define sdxGanttTaskBaseline L"TaskBaseline"
#define sdxGanttTaskTextLabel L"TaskTextLabel"
#define sdxGanttTaskTextLabelHorizontalIndent L"HorizontalIndent"
#define sdxFilterAddButton L"FilterPanelNodeActionButton"
#define sdxFilterBoolOperatorBackground L"FilterPanelGroupNode"
#define sdxFilterControlBackColor L"FilterControlBackColor"
#define sdxFilterItemCaptionBackground L"FilterPanelProperty"
#define sdxFilterOperatorBackground L"FilterPanelName"
#define sdxFilterPanelBrackets L"FilterPanelGroup"
#define sdxFilterRemoveButton L"FilterPanelButton"
#define sdxFilterValueBackground L"FilterPanelValue"
#define sdxDataRowLayoutElement L"DataRowLayoutElement"
#define sdxDataRowLayoutItem L"DataRowLayoutItem"
#define sdxItem L"Item"
#define sdxItems L"Items"
#define sdxAlpha L"Alpha"
#define sdxControlParts L"ControlParts"
#define sdxDisplayName L"DisplayName"
#define sdxGlyph L"Glyph"
#define sdxImage L"Image"
#define sdxName L"Name"
#define sdxParentName L"Parent"
#define sdxPart L"Part"
#define sdxVersion L"Version"
#define sdxSkinGroupName L"SkinGroupName"
#define sdxSkinIcon L"SkinIcon"
#define sdxSkinIconLarge L"SkinIconLarge"
#define sdxSkinDefaultGroupName L"Custom Skins"
#define sdxSkinDefaultSkinIcon L"DEFAULTSKINICONSMALL"
#define sdxSkinDefaultSkinIconLarge L"DEFAULTSKINICONLARGE"
#define sdxLayoutHorz L"Horizontal"
#define sdxLayoutVert L"Vertical"
#define sdxAlphaColor L"AlphaColor"
#define sdxBoolean L"Boolean"
#define sdxColor L"Color"
#define sdxContent L"Content"
#define sdxContentOffsets L"ContentOffsets"
#define sdxImageCount L"ImageCount"
#define sdxInterpolationMode L"InterpolationMode"
#define sdxRect L"Rect"
#define sdxScaled L"Scaled"
#define sdxSize L"Size"
#define sdxString L"String"
#define sdxTextColor L"TextColor"
#define sdxStretch L"Stretch"
#define sdxTile L"Tile"
#define sdxNoResize L"NoResize"
#define sdxFile L"File"
#define sdxLayout L"Layout"
#define sdxStates L"States"
#define sdxMargins L"Margins"
#define sdxBorders L"Borders"
#define sdxBordersInner L"BordersInner"
#define sdxThin L"Thin"
#define sdxLeft L"Left"
#define sdxTop L"Top"
#define sdxRight L"Right"
#define sdxBottom L"Bottom"
#define sdxWidth L"Width"
#define sdxHeight L"Height"
#define sdxGradientBeginColor L"GradientBeginColor"
#define sdxGradientEndColor L"GradientEndColor"
#define sdxGradientMode L"GradientMode"
#define sdxGradientModeBackwardDiagonal L"BackwardDiagonal"
#define sdxGradientModeForwardDiagonal L"ForwardDiagonal"
#define sdxGradientModeHorizontal L"Horizontal"
#define sdxGradientModeVertical L"Vertical"
extern DELPHI_PACKAGE Dxskinsstrs__1 dxDefaultColorPaletteItems;
extern DELPHI_PACKAGE Dxskinsstrs__2 dxDefaultGlyphColorPaletteItems;
extern DELPHI_PACKAGE Dxskinsstrs__3 CalcEditTextColorsMap;
extern DELPHI_PACKAGE Dxskinsstrs__4 BreadcrumbEditBackgroundColorsMap;
extern DELPHI_PACKAGE Dxskinsstrs__5 BreadcrumbEditBordersColorsMap;
extern DELPHI_PACKAGE Dxskinsstrs__6 CommonGroup;
extern DELPHI_PACKAGE Dxskinsstrs__7 GanttGroup;
extern DELPHI_PACKAGE Dxskinsstrs__8 GridGroup;
extern DELPHI_PACKAGE Dxskinsstrs__9 VGridGroup;
extern DELPHI_PACKAGE Dxskinsstrs__01 FormGroup;
extern DELPHI_PACKAGE Dxskinsstrs__11 EditButtonsMap;
extern DELPHI_PACKAGE Dxskinsstrs__21 FormFrameMap;
extern DELPHI_PACKAGE Dxskinsstrs__31 EditBackgroundColorsMap;
extern DELPHI_PACKAGE Dxskinsstrs__41 EditTextColorsMap;
extern DELPHI_PACKAGE Dxskinsstrs__51 LayoutViewElementPaddingMap;
extern DELPHI_PACKAGE Dxskinsstrs__61 LayoutViewElementSpacingMap;
extern DELPHI_PACKAGE Dxskinsstrs__71 ProgressBarPartNameMap;
}	/* namespace Dxskinsstrs */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DXSKINSSTRS)
using namespace Dxskinsstrs;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// DxskinsstrsHPP
